#!/bin/bash
for var1 in 32 40 48 56 64
do
    cp parameters.sh parameters_tmp.sh
    sed -i.bak "s/XXX/${var1}/g" parameters_tmp.sh
    make parameters=parameters_tmp.sh
    ./run
    make clean
done
rm *.bak
rm parameters_tmp.sh
